defmodule SurveyPulse.Repo.Migrations.DropSurveyStatus do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:surveys) do
      remove :status
    end
  end

  def down do
    alter table(:surveys) do
      add :status, :text, default: "active"
    end
  end
end
