defmodule SurveyPulse.Repo.Migrations.CreateSurveys do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:waves, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :wave_number, :bigint, null: false
      add :label, :text
      add :started_at, :utc_datetime, null: false
      add :ended_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :survey_id, :uuid, null: false
    end

    create table(:surveys, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:waves) do
      modify :survey_id,
             references(:surveys,
               column: :id,
               name: "waves_survey_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:surveys) do
      add :name, :text, null: false
      add :description, :text
      add :category, :text, null: false
      add :status, :text, default: "active"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:questions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :code, :text, null: false
      add :text, :text, null: false
      add :question_type, :text, null: false
      add :scale_min, :bigint, default: 1
      add :scale_max, :bigint, default: 5

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :survey_id,
          references(:surveys,
            column: :id,
            name: "questions_survey_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:questions, "questions_survey_id_fkey")

    drop table(:questions)

    alter table(:surveys) do
      remove :updated_at
      remove :inserted_at
      remove :status
      remove :category
      remove :description
      remove :name
    end

    drop constraint(:waves, "waves_survey_id_fkey")

    alter table(:waves) do
      modify :survey_id, :uuid
    end

    drop table(:surveys)

    drop table(:waves)
  end
end
